#!/bin/sh
#
# Copyright (C) 2014 Dream Property GmbH
#

set -e

DEVICE=/dev/mmcblk0
OPTION=

STDOUT=/dev/null
TEMP=
VERBOSE=1

is_blockdev()
{
	[ -b "${1}" ]
}

is_writeable()
{
	[ -w "${1}" ]
}

is_writeable_blockdev()
{
	is_blockdev "${1}" && is_writeable "${1}"
}

is_empty()
{
	[ -z "${1}" ]
}

abort()
{
	echo "Fatal: $@"
	exit 1
}

info()
{
	is_empty "${VERBOSE}" || echo "[*] $@"
}

select_boot_source()
{
	info "Enabling boot source ${2}"
	printf "opt${2}\0" | dd of=${1} bs=512 seek=64 conv=fsync >${STDOUT} 2>&1
}

usage()
{
	echo "Usage: ${0} [-hqtv] [-d <device>] [A|B|C]"
	echo "       Default: -d ${DEVICE}"
	exit ${1}
}

while getopts d:hqtv opt; do
	case "${opt}" in
		d)
			DEVICE="${OPTARG}"
			;;
		q)
			VERBOSE=
			;;
		t)
			set -x
			;;
		v)
			STDOUT=/dev/stdout
			;;
		h|?)
			if [ "$opt" = "h" ]; then
				usage 0
			else
				usage 1
			fi
			;;
	esac
done

shift $((${OPTIND} - 1))
[ "$#" -eq 1 ] || usage 1
OPTION=${1}

is_writeable_blockdev "${DEVICE}" || abort "Target block device '${DEVICE}' is not a writeable block device"
! is_empty "${OPTION}" || abort "No option given"

case "${OPTION}" in
	A|B|C)
		;;
	*)
		abort "Invalid boot option: ${OPTION}"
		;;
esac

select_boot_source "${DEVICE}" "${OPTION}" || abort "Failed to enable boot source"
