#!/bin/sh
if [ -f /proc/stb/fp/boot_mode ]; then
	echo rescue >/proc/stb/fp/boot_mode && reboot
else
	echo "Sorry, manual intervention required! Please execute 'reboot' manually,"
	echo "then press the front panel power button and keep it pressed while your"
	echo "Dreambox restarts, until the countdown on the front panel display has"
	echo "elapsed."
	exit 1
fi
